apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: messaging-k8s
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/Auruscent/messaging-k8s
  ref:
    branch: main
  secretRef:
    name: messaging-k8s-deploy-key
